#!/usr/bin/perl -w

use strict;
use warnings;
use Getopt::Long qw(:config no_ignore_case);
use Config::JSON;

our $VERBOSITY = 0;

use constant {
	STATE_OK => 0,
	STATE_WARNING => 1,
	STATE_CRITICAL => 2,
	STATE_UNKNOWN => 3,
};

our @hdrmap_a = ('ID#','ATTRIBUTE_NAME','FLAG','VALUE','WORST','THRESH',
	'TYPE','UPDATED','WHEN_FAILED','RAW_VALUE');

sub getSmartctl{
	my $smartctl = shift;
	my $device = shift;
	my @output = `$smartctl -a $device`;
	return \@output;
}

sub readDbJSON{
	my $dbJSON = shift;
	return(Config::JSON->new($dbJSON));
}

sub checkWhichDevice{
	my $dbConfig = shift;
	my @smartctlOut = @{(shift)};
	# Fetch the model lines from smart output
	my @device = grep { /Model Family/i || /Device Model/i } @smartctlOut;

	# Fetch the device JSON hash
	my $devices_h = $dbConfig->get("Devices");
	foreach my $key (keys %$devices_h){
		# Return model strings and IDs if device is found
		foreach(@device){
			if(($_ =~ $devices_h->{$key}->{'Device'}->[0]) ||
			($_ =~ $devices_h->{$key}->{'Device'}->[1])){
				return ($devices_h->{$key}->{'Device'},$devices_h->{$key}->{'ID#'},
				$devices_h->{$key}->{'Threshs'});
			}
		}
	}
}

sub parseSmartctlOut{
	my @smartctlOut = @{(shift)};
	# Check for smart value lines
	my @smartValues;
	my @splittedLine;
	foreach my $line (@smartctlOut) {
		if($line =~ /\d+\s+\w+\s+0x\d+\s+\d+\s+\d+\s+\d+\s+\w+/){
			$line =~ s/^\s+|\s+$//g;
			# Split the found line, and map its elements
			# The header map defines the keys for the hash
			@splittedLine = map { s/^\s*//; s/\s*$//; $_; } split(/\s+/,$line);
			my %lineValues_h;
			for(my $i = 0; $i < @splittedLine; $i++){
				$lineValues_h{$hdrmap_a[$i]} = $splittedLine[$i];
			}
			push @smartValues, \%lineValues_h;
		}
	}
	return \@smartValues;
}

sub checkSmartctl{
	my @smartValues_a = @{(shift)};
	my %IDs_h = %{(shift)};
	my %threshs_h = %{(shift)};
	my @warnings_a;
	my @criticals_a;
	my @statusLevel_a = ("OK");

	# TODO Check conditions for threshs
	foreach my $row (@smartValues_a){
		my $ID = $row->{'ID#'};
		if(exists $IDs_h{$ID} && exists $threshs_h{$ID}){
			if($row->{$IDs_h{$ID}} < $threshs_h{$ID}->[0]){
				$statusLevel_a[0] = 'Warning';
				push @warnings_a, $row->{'ATTRIBUTE_NAME'};
			}
			if($row->{$IDs_h{$ID}} < $threshs_h{$ID}->[0]){
				$statusLevel_a[0] = 'Critical';
				pop @warnings_a;
				push @criticals_a, $row->{'ATTRIBUTE_NAME'};
			}
		}
	}

	push @statusLevel_a, \@warnings_a;
	push @statusLevel_a, \@criticals_a;
	return \@statusLevel_a;
}

sub getStatusString{
	my $level = shift;
	my @statusLevel_a = @{(shift)};
	my $verbosity = shift;
	my @sensors_a;
	my $status_string = "";

	if($level eq "Warning"){
		@sensors_a = @{$statusLevel_a[1]};
	}
	if($level eq "Critical"){
		@sensors_a = @{$statusLevel_a[2]};
	}

	# Collect performance data of warn and crit sensors
	if($level eq "Warning" || $level eq "Critical"){
		if(@sensors_a){
			foreach my $sensor (@sensors_a){
				$status_string .= "[".$sensor." = ".$level;
				#if($verbosity && exists $PERF_DATA[0]->{$sensor}){
				#	$status_string .= " (".$PERF_DATA[0]->{$sensor}.")";
				#}
				$status_string .= "]";
			}
		}
	}
	return $status_string;
}

MAIN: {
	my ($smartctl, $device, $dbJSON, $exitCode);
	if ( !(GetOptions(
		'v|verbose' => sub { $VERBOSITY = 1 },
		'vv' => sub { $VERBOSITY = 2 },
		'vvv' => sub { $VERBOSITY = 3 },
		'h|help' => sub {displayHelp();},
		'p|path=s' => \$smartctl,
		'd|device=s' => \$device,
		'dbj|dbjson=s' => \$dbJSON
	)))	{
		displayUsage();
		exit(STATE_UNKNOWN);
	}
	# Check smartclt tool
	if(!defined($smartctl)){
		$smartctl = "/usr/sbin/smartctl";
	}
	# The device must be present
	if(!defined($device)){
		print "Error: smartctl requires a valid device name.\n";
		displayUsage();
		exit(STATE_UNKNOWN);
	}
	my $output = getSmartctl($smartctl,$device);
	my $dbConfig = readDbJSON($dbJSON);
	my ($deviceName,$IDs_h,$threshs_h) = checkWhichDevice($dbConfig,$output);
	my $smartValues_a = parseSmartctlOut($output);
	my $statusLevel_a = checkSmartctl($smartValues_a,$IDs_h,$threshs_h);
	if($statusLevel_a->[0] eq "Critical"){
		$exitCode = STATE_CRITICAL;
	}
	if($statusLevel_a->[0] eq "Warning"){
		$exitCode = STATE_WARNING;
	}
	print $statusLevel_a->[0]." - ".$deviceName->[0]." ";
	print getStatusString("Critical",$statusLevel_a,$VERBOSITY);
	print getStatusString("Warning",$statusLevel_a,$VERBOSITY);
	exit ($exitCode);
}